server:
  port: 8888
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  #数据源
  datasource:
    url : jdbc:mysql://123.207.124.113:3306/SEproject
    username : admin
    password : mysql
    driverClassName : com.mysql.jdbc.Driver
  #数据持久层
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  #安全框架
  security:
    user:
      name: admin
      password: admin
  #邮件发送
  mail:
    host: smtp.163.com
    username: fateiceb@163.com
    password: zq123456789

#热部署
devtools:
  restart:
    enabled: true #热部署生效